### ISSUE TITLE
Using compression adapter results on empty database

### ISSUE THREAD

**Issue by samuelstein** [gabrielcsapo/node-flat-db#15]
Hello,
i try to use your database with the compression adapter and a persisted file but the database object seems to be always null. With the synchronous adapter it is working. What i'm doing wrong?
My code:
`const storage = require('node-flat-db/file-compress-sync')
db = flat('test.json', { storage: storage })  
console.log('db.object')`

**Comment by gabrielcsapo** [comment]
```javascript
const flat = require('node-flat-db');
const storage = require('node-flat-db/file-compress-sync');
db = flat('test.json', { storage: storage });
db('planets').push({name: 'earth'});
console.log(db.object);
```

should render `{ planets: [ { name: 'earth' } ] }`

what do you get @samuelstein?

**Comment by samuelstein** [comment]
yeah this is working. thanks for clearing. but i want to use a json file as data source. with that the database is always null.

**Comment by gabrielcsapo** [comment]
@samuelstein could you give an example? The one above has a JSON data source

**Comment by samuelstein** [comment]
sorry. let me clarify this. i'm having a gzip compressed json file with lots of data as database file. when i try to read from it with your coding example (https://github.com/gabrielcsapo/node-flat-db/issues/15#issuecomment-299758948) it does not give me values back.

**Comment by gabrielcsapo** [comment]
@samuelstein did you gzip the file with the storage option or is this from another project? Because the compress storage option is using lzstring to do that compression instead of gzip. (https://github.com/gabrielcsapo/node-flat-db/blob/master/src/file-compress-sync.js#L16)

**Comment by samuelstein** [comment]
ahhh shit. you're right. the storage is lzstring compressed and not gzip. sorry was my error in reasoning. it is now working as expected. thanks for patience.

**Comment by gabrielcsapo** [comment]
@samuelstein I am glad it worked! How did you get it working? 😊

**Comment by samuelstein** [comment]
using a lzstring compressed json file as database.
